// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqr9mFWYy-Hn-bcsJk0uzQ1j7Vr762ucw',
    appId: '1:530345749490:web:2adc4e7aac0e53c06a196b',
    messagingSenderId: '530345749490',
    projectId: 'flash-chat-v2-86ba6',
    authDomain: 'flash-chat-v2-86ba6.firebaseapp.com',
    storageBucket: 'flash-chat-v2-86ba6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANT-5wsMo6_Zl4rH5wvuFr9M9MoifZ9t4',
    appId: '1:530345749490:android:426954998f987e356a196b',
    messagingSenderId: '530345749490',
    projectId: 'flash-chat-v2-86ba6',
    storageBucket: 'flash-chat-v2-86ba6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaHTw5FznzOUUvsv7gJhpXLQNpkjXThT4',
    appId: '1:530345749490:ios:fc41ba146b2768f66a196b',
    messagingSenderId: '530345749490',
    projectId: 'flash-chat-v2-86ba6',
    storageBucket: 'flash-chat-v2-86ba6.appspot.com',
    iosBundleId: 'com.example.flashChatV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaHTw5FznzOUUvsv7gJhpXLQNpkjXThT4',
    appId: '1:530345749490:ios:fc41ba146b2768f66a196b',
    messagingSenderId: '530345749490',
    projectId: 'flash-chat-v2-86ba6',
    storageBucket: 'flash-chat-v2-86ba6.appspot.com',
    iosBundleId: 'com.example.flashChatV2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqr9mFWYy-Hn-bcsJk0uzQ1j7Vr762ucw',
    appId: '1:530345749490:web:fab30cfe1f41c5aa6a196b',
    messagingSenderId: '530345749490',
    projectId: 'flash-chat-v2-86ba6',
    authDomain: 'flash-chat-v2-86ba6.firebaseapp.com',
    storageBucket: 'flash-chat-v2-86ba6.appspot.com',
  );
}
